## NACHO

In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [3]:
df = pd.read_csv('../df_cleaned.csv')

In [4]:
df.drop(columns='Unnamed: 0', inplace=True)

In [5]:
df

index  age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  \
0        0   51    1   1     125.0  213.0  0.0      2.0    125.0    1.0   
1        1   54    1   3     120.0  237.0  0.0      0.0    150.0    1.0   
2        2   63    1   4     140.0    0.0  NaN      2.0    149.0    0.0   
3        3   52    0   2     140.0    NaN  0.0      0.0    140.0    0.0   
4        4   55    1   4     140.0  217.0  0.0      0.0    111.0    1.0   
..     ...  ...  ...  ..       ...    ...  ...      ...      ...    ...   
911    179   54    1   4     200.0  198.0  0.0      0.0    142.0    1.0   
912    180   55    1   2     110.0  214.0  1.0      1.0    180.0    0.0   
913    181   67    1   3     152.0  212.0  0.0      2.0    150.0    0.0   
914    182   59    1   1     170.0  288.0  0.0      2.0    159.0    0.0   
915    183   58    1   4       NaN  203.0  1.0      0.0      NaN    NaN   

     oldpeak  slope   ca  thal  label  
0        1.4    1.0  1.0   3.0    0.0  
1        1.5    NaN  NaN   7.0    2.0  
2        2.0    1.0  NaN   NaN    2.0  
3        0.0    NaN  NaN   NaN    0.0  
4        5.6    3.0  0.0   7.0    3.0  
..       ...    ...  ...   ...    ...  
911      2.0    2.0  NaN   NaN    NaN  
912      NaN    NaN  NaN   NaN    NaN  
913      0.8    2.0  0.0   7.0    NaN  
914      0.2    2.0  0.0   7.0    NaN  
915      NaN    NaN  NaN   NaN    NaN  

[916 rows x 15 columns]

In [6]:
df.drop('index', axis=1, inplace=True)

In [7]:
df

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     51    1   1     125.0  213.0  0.0      2.0    125.0    1.0      1.4   
1     54    1   3     120.0  237.0  0.0      0.0    150.0    1.0      1.5   
2     63    1   4     140.0    0.0  NaN      2.0    149.0    0.0      2.0   
3     52    0   2     140.0    NaN  0.0      0.0    140.0    0.0      0.0   
4     55    1   4     140.0  217.0  0.0      0.0    111.0    1.0      5.6   
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...   
911   54    1   4     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912   55    1   2     110.0  214.0  1.0      1.0    180.0    0.0      NaN   
913   67    1   3     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914   59    1   1     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915   58    1   4       NaN  203.0  1.0      0.0      NaN    NaN      NaN   

     slope   ca  thal  label  
0      1.0  1.0   3.0    0.0  
1      NaN  NaN   7.0    2.0  
2      1.0  NaN   NaN    2.0  
3      NaN  NaN   NaN    0.0  
4      3.0  0.0   7.0    3.0  
..     ...  ...   ...    ...  
911    2.0  NaN   NaN    NaN  
912    NaN  NaN   NaN    NaN  
913    2.0  0.0   7.0    NaN  
914    2.0  0.0   7.0    NaN  
915    NaN  NaN   NaN    NaN  

[916 rows x 14 columns]

In [8]:
df.replace({'<NA>':np.nan}, inplace=True)

In [9]:
df

age  sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0     51    1   1     125.0  213.0  0.0      2.0    125.0    1.0      1.4   
1     54    1   3     120.0  237.0  0.0      0.0    150.0    1.0      1.5   
2     63    1   4     140.0    0.0  NaN      2.0    149.0    0.0      2.0   
3     52    0   2     140.0    NaN  0.0      0.0    140.0    0.0      0.0   
4     55    1   4     140.0  217.0  0.0      0.0    111.0    1.0      5.6   
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...   
911   54    1   4     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912   55    1   2     110.0  214.0  1.0      1.0    180.0    0.0      NaN   
913   67    1   3     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914   59    1   1     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915   58    1   4       NaN  203.0  1.0      0.0      NaN    NaN      NaN   

     slope   ca  thal  label  
0      1.0  1.0   3.0    0.0  
1      NaN  NaN   7.0    2.0  
2      1.0  NaN   NaN    2.0  
3      NaN  NaN   NaN    0.0  
4      3.0  0.0   7.0    3.0  
..     ...  ...   ...    ...  
911    2.0  NaN   NaN    NaN  
912    NaN  NaN   NaN    NaN  
913    2.0  0.0   7.0    NaN  
914    2.0  0.0   7.0    NaN  
915    NaN  NaN   NaN    NaN  

[916 rows x 14 columns]

In [10]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps    float64
chol        float64
fbs         float64
restecg     float64
thalach     float64
exang       float64
oldpeak     float64
slope       float64
ca          float64
thal        float64
label       float64
dtype: object

In [11]:
numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']
# Convertir columnas numéricas de nuevo a tipo numérico
df[numeric_cols] = df[numeric_cols].astype(float)

# Convertir columnas categóricas de nuevo a tipo categórico
df[categorical_cols] = df[categorical_cols].astype('category')

# Verificar que los dtypes han cambiado
print(df.dtypes)


age          float64
sex         category
cp          category
trestbps     float64
chol         float64
fbs         category
restecg     category
thalach      float64
exang       category
oldpeak      float64
slope       category
ca          category
thal        category
label        float64
dtype: object


In [12]:
df

age sex cp  trestbps   chol  fbs restecg  thalach exang  oldpeak slope  \
0    51.0   1  1     125.0  213.0  0.0     2.0    125.0   1.0      1.4   1.0   
1    54.0   1  3     120.0  237.0  0.0     0.0    150.0   1.0      1.5   NaN   
2    63.0   1  4     140.0    0.0  NaN     2.0    149.0   0.0      2.0   1.0   
3    52.0   0  2     140.0    NaN  0.0     0.0    140.0   0.0      0.0   NaN   
4    55.0   1  4     140.0  217.0  0.0     0.0    111.0   1.0      5.6   3.0   
..    ...  .. ..       ...    ...  ...     ...      ...   ...      ...   ...   
911  54.0   1  4     200.0  198.0  0.0     0.0    142.0   1.0      2.0   2.0   
912  55.0   1  2     110.0  214.0  1.0     1.0    180.0   0.0      NaN   NaN   
913  67.0   1  3     152.0  212.0  0.0     2.0    150.0   0.0      0.8   2.0   
914  59.0   1  1     170.0  288.0  0.0     2.0    159.0   0.0      0.2   2.0   
915  58.0   1  4       NaN  203.0  1.0     0.0      NaN   NaN      NaN   NaN   

      ca thal  label  
0    1.0  3.0    0.0  
1    NaN  7.0    2.0  
2    NaN  NaN    2.0  
3    NaN  NaN    0.0  
4    0.0  7.0    3.0  
..   ...  ...    ...  
911  NaN  NaN    NaN  
912  NaN  NaN    NaN  
913  0.0  7.0    NaN  
914  0.0  7.0    NaN  
915  NaN  NaN    NaN  

[916 rows x 14 columns]

In [13]:
# Suponiendo que 'df' es tu DataFrame y 'df' es tu DataFrame final
# Convertir '<NA>' a NaN
df.replace('<NA>', np.nan, inplace=True)

# Obtener columnas numéricas y categóricas
numeric_cols = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
categorical_cols = ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal', 'label']

# Imputación para variables numéricas (usando la mediana)
numeric_imputer = SimpleImputer(strategy='median')
df[numeric_cols] = numeric_imputer.fit_transform(df[numeric_cols])

# Imputación para variables categóricas (usando la moda)
categorical_imputer = SimpleImputer(strategy='most_frequent')
df[categorical_cols] = categorical_imputer.fit_transform(df[categorical_cols])

# Verificar que ya no hay valores faltantes
print(df.isnull().sum())

# El DataFrame 'df' ahora contiene los valores imputados


age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
label       0
dtype: int64


In [14]:
df

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    51.0  1.0  1.0     125.0  213.0  0.0      2.0    125.0    1.0      1.4   
1    54.0  1.0  3.0     120.0  237.0  0.0      0.0    150.0    1.0      1.5   
2    63.0  1.0  4.0     140.0    0.0  0.0      2.0    149.0    0.0      2.0   
3    52.0  0.0  2.0     140.0  223.0  0.0      0.0    140.0    0.0      0.0   
4    55.0  1.0  4.0     140.0  217.0  0.0      0.0    111.0    1.0      5.6   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0      0.5   
913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0      0.5   

     slope   ca  thal  label  
0      1.0  1.0   3.0    0.0  
1      2.0  0.0   7.0    2.0  
2      1.0  0.0   3.0    2.0  
3      2.0  0.0   3.0    0.0  
4      3.0  0.0   7.0    3.0  
..     ...  ...   ...    ...  
911    2.0  0.0   3.0    0.0  
912    2.0  0.0   3.0    0.0  
913    2.0  0.0   7.0    0.0  
914    2.0  0.0   7.0    0.0  
915    2.0  0.0   3.0    0.0  

[916 rows x 14 columns]

In [15]:
train_end = df[0:732]
test_end = df[(916-184):]

In [16]:
test_end

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0      3.0   
733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0      0.0   
734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0      0.0   
735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0      2.5   
736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0      0.6   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0      0.5   
913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0      0.5   

     slope   ca  thal  label  
732    3.0  0.0   3.0    0.0  
733    2.0  0.0   3.0    0.0  
734    2.0  0.0   3.0    0.0  
735    3.0  0.0   3.0    0.0  
736    1.0  0.0   3.0    0.0  
..     ...  ...   ...    ...  
911    2.0  0.0   3.0    0.0  
912    2.0  0.0   3.0    0.0  
913    2.0  0.0   7.0    0.0  
914    2.0  0.0   7.0    0.0  
915    2.0  0.0   3.0    0.0  

[184 rows x 14 columns]

In [17]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

# Identificar la variable objetivo y las características para el entrenamiento
target_column = 'label'  # Nombre real de la variable objetivo
features_train = train_end.drop(columns=[target_column])
target_train = train_end[target_column]

# Identificar las características para la predicción en el conjunto de prueba
features_test = test_end.drop(columns=[target_column])

# Inicializar y entrenar el modelo de Random Forest para clasificación
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(features_train, target_train)

# Predecir las clases de las variables categóricas faltantes en el conjunto de prueba
predicted_classes = model.predict(features_test)

# Crear un nuevo DataFrame con las clases predichas
predicted_df = test_end.copy()
predicted_df[target_column] = predicted_classes

# Imprimir el DataFrame con las clases predichas
print(predicted_df)


      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0      3.0   
733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0      0.0   
734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0      0.0   
735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0      2.5   
736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0      0.6   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0      0.5   
913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0      0.5   

     slope   ca  thal  label  
732    3.0  0.0   3.

In [18]:
predicted_df['index'] = predicted_df.index

In [19]:
predicted_df.reset_index(inplace=True)

In [20]:
predicted_df

level_0   age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  \
0        732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0   
1        733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0   
2        734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0   
3        735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0   
4        736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0   
..       ...   ...  ...  ...       ...    ...  ...      ...      ...    ...   
179      911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0   
180      912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0   
181      913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0   
182      914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0   
183      915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0   

     oldpeak  slope   ca  thal  label  index  
0        3.0    3.0  0.0   3.0    2.0    732  
1        0.0    2.0  0.0   3.0    0.0    733  
2        0.0    2.0  0.0   3.0    0.0    734  
3        2.5    3.0  0.0   3.0    1.0    735  
4        0.6    1.0  0.0   3.0    0.0    736  
..       ...    ...  ...   ...    ...    ...  
179      2.0    2.0  0.0   3.0    2.0    911  
180      0.5    2.0  0.0   3.0    0.0    912  
181      0.8    2.0  0.0   7.0    0.0    913  
182      0.2    2.0  0.0   7.0    0.0    914  
183      0.5    2.0  0.0   3.0    1.0    915  

[184 rows x 16 columns]

In [21]:
predicted_df.drop(columns=['index'], inplace=True)

# Renombrar la columna 'level_0' a 'index'
predicted_df.rename(columns={'level_0': 'index'}, inplace=True)

predicted_df['ID'] = range(len(predicted_df))
# Guardar las columnas 'index' y 'label' en un archivo CSV
predicted_df[['ID', 'label']].to_csv('try1_data.csv', index=False)

In [22]:
predicted_df

index   age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  \
0      732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0   
1      733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0   
2      734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0   
3      735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0   
4      736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0   
..     ...   ...  ...  ...       ...    ...  ...      ...      ...    ...   
179    911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0   
180    912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0   
181    913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0   
182    914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0   
183    915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0   

     oldpeak  slope   ca  thal  label   ID  
0        3.0    3.0  0.0   3.0    2.0    0  
1        0.0    2.0  0.0   3.0    0.0    1  
2        0.0    2.0  0.0   3.0    0.0    2  
3        2.5    3.0  0.0   3.0    1.0    3  
4        0.6    1.0  0.0   3.0    0.0    4  
..       ...    ...  ...   ...    ...  ...  
179      2.0    2.0  0.0   3.0    2.0  179  
180      0.5    2.0  0.0   3.0    0.0  180  
181      0.8    2.0  0.0   7.0    0.0  181  
182      0.2    2.0  0.0   7.0    0.0  182  
183      0.5    2.0  0.0   3.0    1.0  183  

[184 rows x 16 columns]

In [23]:
try1_df = pd.read_csv('try1_data.csv')

In [24]:
try1_df

ID  label
0      0    2.0
1      1    0.0
2      2    0.0
3      3    1.0
4      4    0.0
..   ...    ...
179  179    2.0
180  180    0.0
181  181    0.0
182  182    0.0
183  183    1.0

[184 rows x 2 columns]

In [25]:
try1_df['label'].value_counts()

0.0    101
1.0     39
2.0     25
3.0     19
Name: label, dtype: int64

In [26]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# Crear un modelo de clasificador SVM
svm_model = make_pipeline(StandardScaler(), SVC(kernel='linear', C=1.0, random_state=42))

# Entrenar el modelo SVM
svm_model.fit(features_train, target_train)

# Predecir las clases en el conjunto de prueba
predicted_classes_svm = svm_model.predict(features_test)

# Crear un nuevo DataFrame con las clases predichas por SVM
predicted_df_svm = test_end.copy()
predicted_df_svm[target_column] = predicted_classes_svm

# Imprimir el DataFrame con las clases predichas por SVM
print(predicted_df_svm)


      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0      3.0   
733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0      0.0   
734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0      0.0   
735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0      2.5   
736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0      0.6   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0      0.5   
913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0      0.5   

     slope   ca  thal  label  
732    3.0  0.0   3.

In [27]:
predicted_df_svm['index'] = predicted_df.index
predicted_df_svm.reset_index(inplace=True)

In [28]:
predicted_df_svm.drop(columns=['index'], inplace=True)

# Renombrar la columna 'level_0' a 'index'
predicted_df_svm.rename(columns={'level_0': 'index'}, inplace=True)

predicted_df_svm['ID'] = range(len(predicted_df_svm))
# Guardar las columnas 'index' y 'label' en un archivo CSV
predicted_df_svm[['ID', 'label']].to_csv('try2_data.csv', index=False)

In [29]:
try2_df = pd.read_csv('try2_data.csv')

In [30]:
try2_df

ID  label
0      0    2.0
1      1    0.0
2      2    0.0
3      3    2.0
4      4    0.0
..   ...    ...
179  179    2.0
180  180    0.0
181  181    0.0
182  182    0.0
183  183    0.0

[184 rows x 2 columns]

In [31]:
try2_df['label'].value_counts()

0.0    101
1.0     46
3.0     24
2.0     13
Name: label, dtype: int64

In [32]:
from sklearn.neighbors import KNeighborsClassifier

# Crear un modelo de clasificador KNN
knn_model = KNeighborsClassifier(n_neighbors=5)

# Entrenar el modelo KNN
knn_model.fit(features_train, target_train)

# Predecir las clases en el conjunto de prueba
predicted_classes_knn = knn_model.predict(features_test)

# Crear un nuevo DataFrame con las clases predichas por KNN
predicted_df_knn = test_end.copy()
predicted_df_knn[target_column] = predicted_classes_knn

# Imprimir el DataFrame con las clases predichas por KNN
print(predicted_df_knn)


      age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
732  57.0  1.0  4.0     156.0  173.0  0.0      2.0    119.0    1.0      3.0   
733  52.0  1.0  2.0     160.0  196.0  0.0      0.0    165.0    0.0      0.0   
734  48.0  1.0  2.0     100.0  223.0  0.0      0.0    100.0    0.0      0.0   
735  62.0  1.0  4.0     115.0    0.0  0.0      0.0    128.0    1.0      2.5   
736  51.0  1.0  3.0     110.0  175.0  0.0      0.0    123.0    0.0      0.6   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
911  54.0  1.0  4.0     200.0  198.0  0.0      0.0    142.0    1.0      2.0   
912  55.0  1.0  2.0     110.0  214.0  1.0      1.0    180.0    0.0      0.5   
913  67.0  1.0  3.0     152.0  212.0  0.0      2.0    150.0    0.0      0.8   
914  59.0  1.0  1.0     170.0  288.0  0.0      2.0    159.0    0.0      0.2   
915  58.0  1.0  4.0     130.0  203.0  1.0      0.0    140.0    0.0      0.5   

     slope   ca  thal  label  
732    3.0  0.0   3.

In [33]:
predicted_df_knn['index'] = predicted_df_knn.index
predicted_df_knn.reset_index(inplace=True)
predicted_df_knn.drop(columns=['index'], inplace=True)

# Renombrar la columna 'level_0' a 'index'
predicted_df_knn.rename(columns={'level_0': 'index'}, inplace=True)

predicted_df_knn['ID'] = range(len(predicted_df_knn))
# Guardar las columnas 'index' y 'label' en un archivo CSV
predicted_df_knn[['ID', 'label']].to_csv('try3_data.csv', index=False)

In [34]:
try3_df = pd.read_csv('try3_data.csv')

In [35]:
try3_df['label'].value_counts()

0.0    119
1.0     35
2.0     20
3.0     10
Name: label, dtype: int64

In [36]:
try3_df

ID  label
0      0    0.0
1      1    0.0
2      2    0.0
3      3    1.0
4      4    3.0
..   ...    ...
179  179    0.0
180  180    0.0
181  181    0.0
182  182    0.0
183  183    0.0

[184 rows x 2 columns]

## VARIABLE SCORE_BY_COR

In [96]:
df_nuevo_train = pd.get_dummies(train_end, columns= ['restecg', 'cp', 'ca', 'slope', 'thal', 'sex', 'fbs', 'exang'])


In [97]:
df_nuevo_train

age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
0    51.0     125.0  213.0    125.0      1.4    0.0            0            0   
1    54.0     120.0  237.0    150.0      1.5    2.0            1            0   
2    63.0     140.0    0.0    149.0      2.0    2.0            0            0   
3    52.0     140.0  223.0    140.0      0.0    0.0            1            0   
4    55.0     140.0  217.0    111.0      5.6    3.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
727  46.0     120.0  230.0    150.0      0.0    0.0            1            0   
728  62.0     130.0  204.0    140.0      0.5    1.0            0            1   
729  43.0     122.0  213.0    165.0      0.2    0.0            1            0   
730  68.0     150.0  195.0    132.0      0.0    1.0            1            0   
731  41.0     126.0  306.0    163.0      0.0    0.0            1            0   

     restecg_2.0  cp_1.0  ...  slope_3.0  thal_3.0  thal_6.0  thal_7.0  \
0              1       1  ...          0         1         0         0   
1              0       0  ...          0         0         0         1   
2              1       0  ...          0         1         0         0   
3              0       0  ...          0         1         0         0   
4              0       0  ...          1         0         0         1   
..           ...     ...  ...        ...       ...       ...       ...   
727            0       0  ...          0         1         0         0   
728            0       0  ...          0         1         0         0   
729            0       0  ...          0         1         0         0   
730            0       0  ...          0         0         1         0   
731            0       0  ...          0         1         0         0   

     sex_0.0  sex_1.0  fbs_0.0  fbs_1.0  exang_0.0  exang_1.0  
0          0        1        1        0          0          1  
1          0        1        1        0          0          1  
2          0        1        1        0          1          0  
3          1        0        1        0          1          0  
4          0        1        1        0          0          1  
..       ...      ...      ...      ...        ...        ...  
727        0        1        1        0          1          0  
728        0        1        1        0          1          0  
729        1        0        1        0          1          0  
730        0        1        0        1          1          0  
731        1        0        1        0          1          0  

[732 rows x 29 columns]

In [98]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X = df_nuevo_train.drop('label', axis=1)
y = df_nuevo_train['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

coef_importance = pd.Series(model.coef_[0], index=X.columns)
coef_importance = coef_importance.abs().sort_values(ascending=False)

print("Variables con mayor peso en el modelo:")
print(coef_importance)

Variables con mayor peso en el modelo:
cp_4.0         0.926446
ca_0.0         0.623091
cp_2.0         0.590465
sex_1.0        0.541102
sex_0.0        0.507406
oldpeak        0.500585
slope_1.0      0.447306
exang_1.0      0.384171
slope_2.0      0.352338
exang_0.0      0.350474
fbs_1.0        0.350308
thal_7.0       0.335155
thal_3.0       0.333945
restecg_1.0    0.320677
restecg_2.0    0.317158
fbs_0.0        0.316611
cp_1.0         0.272075
ca_2.0         0.261436
ca_1.0         0.223855
ca_3.0         0.171497
slope_3.0      0.128665
thal_6.0       0.032487
cp_3.0         0.030209
restecg_0.0    0.030178
age            0.018895
thalach        0.012771
chol           0.003363
trestbps       0.000650
dtype: float64


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [99]:
dict_cor = coef_importance.to_dict()

In [100]:
dict_cor

{'cp_4.0': 0.9264460519278005,
 'ca_0.0': 0.6230908926615831,
 'cp_2.0': 0.5904648087035742,
 'sex_1.0': 0.5411023100610066,
 'sex_0.0': 0.5074055256626558,
 'oldpeak': 0.5005846082917891,
 'slope_1.0': 0.4473060461184159,
 'exang_1.0': 0.3841709107466104,
 'slope_2.0': 0.3523377949172872,
 'exang_0.0': 0.35047412634819314,
 'fbs_1.0': 0.3503080211880254,
 'thal_7.0': 0.3351546793362426,
 'thal_3.0': 0.3339446408984483,
 'restecg_1.0': 0.32067719346014234,
 'restecg_2.0': 0.31715845151308397,
 'fbs_0.0': 0.3166112367882846,
 'cp_1.0': 0.27207543674254336,
 'ca_2.0': 0.26143553709549416,
 'ca_1.0': 0.22385507649273975,
 'ca_3.0': 0.17149706347242696,
 'slope_3.0': 0.12866503560065876,
 'thal_6.0': 0.03248674596094672,
 'cp_3.0': 0.03020902208335622,
 'restecg_0.0': 0.030178042453050734,
 'age': 0.018894680209061224,
 'thalach': 0.012770860883584916,
 'chol': 0.003362866610527904,
 'trestbps': 0.0006502808808741702}

In [101]:
for index, row in df_nuevo_train.iterrows():
    score = 0.0
    for col in df_nuevo_train.columns[:-1]:
        if col in dict_cor: 
            if row[col] == 1:
                score += dict_cor[col] 
    df_nuevo_train.at[index, 'score_by_correlation'] = score


      age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
0    51.0     125.0  213.0    125.0      1.4    0.0            0            0   
1    54.0     120.0  237.0    150.0      1.5    2.0            1            0   
2    63.0     140.0    0.0    149.0      2.0    2.0            0            0   
3    52.0     140.0  223.0    140.0      0.0    0.0            1            0   
4    55.0     140.0  217.0    111.0      5.6    3.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
727  46.0     120.0  230.0    150.0      0.0    0.0            1            0   
728  62.0     130.0  204.0    140.0      0.5    1.0            0            1   
729  43.0     122.0  213.0    165.0      0.2    0.0            1            0   
730  68.0     150.0  195.0    132.0      0.0    1.0            1            0   
731  41.0     126.0  306.0    163.0      0.0    0.0            1            0   

     restecg_2.0  cp_1.0  .

In [102]:
df_nuevo_train

age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
0    51.0     125.0  213.0    125.0      1.4    0.0            0            0   
1    54.0     120.0  237.0    150.0      1.5    2.0            1            0   
2    63.0     140.0    0.0    149.0      2.0    2.0            0            0   
3    52.0     140.0  223.0    140.0      0.0    0.0            1            0   
4    55.0     140.0  217.0    111.0      5.6    3.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
727  46.0     120.0  230.0    150.0      0.0    0.0            1            0   
728  62.0     130.0  204.0    140.0      0.5    1.0            0            1   
729  43.0     122.0  213.0    165.0      0.2    0.0            1            0   
730  68.0     150.0  195.0    132.0      0.0    1.0            1            0   
731  41.0     126.0  306.0    163.0      0.0    0.0            1            0   

     restecg_2.0  cp_1.0  ...  thal_3.0  thal_6.0  thal_7.0  sex_0.0  sex_1.0  \
0              1       1  ...         1         0         0        0        1   
1              0       0  ...         0         0         1        0        1   
2              1       0  ...         1         0         0        0        1   
3              0       0  ...         1         0         0        1        0   
4              0       0  ...         0         0         1        0        1   
..           ...     ...  ...       ...       ...       ...      ...      ...   
727            0       0  ...         1         0         0        0        1   
728            0       0  ...         1         0         0        0        1   
729            0       0  ...         1         0         0        1        0   
730            0       0  ...         0         1         0        0        1   
731            0       0  ...         1         0         0        1        0   

     fbs_0.0  fbs_1.0  exang_0.0  exang_1.0  score_by_correlation  
0          1        0          0          1              2.452053  
1          1        0          0          1              2.612855  
2          1        0          1          0              3.856134  
3          1        0          1          0              3.104507  
4          1        0          0          1              3.285419  
..       ...      ...        ...        ...                   ...  
727        1        0          1          0              2.577948  
728        1        0          1          0              2.868447  
729        1        0          1          0              2.544251  
730        0        1          1          0              2.310187  
731        1        0          1          0              3.199475  

[732 rows x 30 columns]

In [109]:
df_nuevo_test = pd.get_dummies(test_end, columns= ['restecg', 'cp', 'ca', 'slope', 'thal', 'sex', 'fbs', 'exang'])

In [111]:
for index, row in df_nuevo_test.iterrows():
    score = 0.0  
    for col in df_nuevo_test.columns[:-1]:  
        if col in dict_cor: 
            if row[col] == 1: 
                score += dict_cor[col]  
    df_nuevo_test.at[index, 'score_by_correlation'] = score


      age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
732  57.0     156.0  173.0    119.0      3.0    0.0            0            0   
733  52.0     160.0  196.0    165.0      0.0    0.0            1            0   
734  48.0     100.0  223.0    100.0      0.0    0.0            1            0   
735  62.0     115.0    0.0    128.0      2.5    0.0            1            0   
736  51.0     110.0  175.0    123.0      0.6    0.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
911  54.0     200.0  198.0    142.0      2.0    0.0            1            0   
912  55.0     110.0  214.0    180.0      0.5    0.0            0            1   
913  67.0     152.0  212.0    150.0      0.8    0.0            0            0   
914  59.0     170.0  288.0    159.0      0.2    0.0            0            0   
915  58.0     130.0  203.0    140.0      0.5    0.0            1            0   

     restecg_2.0  cp_1.0  .

In [112]:
df_nuevo_test

age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
732  57.0     156.0  173.0    119.0      3.0    0.0            0            0   
733  52.0     160.0  196.0    165.0      0.0    0.0            1            0   
734  48.0     100.0  223.0    100.0      0.0    0.0            1            0   
735  62.0     115.0    0.0    128.0      2.5    0.0            1            0   
736  51.0     110.0  175.0    123.0      0.6    0.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
911  54.0     200.0  198.0    142.0      2.0    0.0            1            0   
912  55.0     110.0  214.0    180.0      0.5    0.0            0            1   
913  67.0     152.0  212.0    150.0      0.8    0.0            0            0   
914  59.0     170.0  288.0    159.0      0.2    0.0            0            0   
915  58.0     130.0  203.0    140.0      0.5    0.0            1            0   

     restecg_2.0  cp_1.0  ...  thal_3.0  thal_6.0  thal_7.0  sex_0.0  sex_1.0  \
732            1       0  ...         1         0         0        0        1   
733            0       0  ...         1         0         0        0        1   
734            0       0  ...         1         0         0        0        1   
735            0       0  ...         1         0         0        0        1   
736            0       0  ...         1         0         0        0        1   
..           ...     ...  ...       ...       ...       ...      ...      ...   
911            0       0  ...         1         0         0        0        1   
912            0       0  ...         1         0         0        0        1   
913            1       0  ...         0         0         1        0        1   
914            1       1  ...         0         0         1        0        1   
915            0       0  ...         1         0         0        0        1   

     fbs_0.0  fbs_1.0  exang_0.0  exang_1.0  score_by_correlation  
732        1        0          0          1              3.187019  
733        1        0          1          0              3.138204  
734        1        0          1          0              3.138204  
735        1        0          0          1              3.284209  
736        1        0          1          0              2.672916  
..       ...      ...        ...        ...                   ...  
911        1        0          0          1              3.507882  
912        0        1          1          0              3.462400  
913        1        0          1          0              2.866139  
914        1        0          1          0              3.108005  
915        0        1          1          0              3.507882  

[184 rows x 30 columns]

In [114]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer

target_column = 'label'
features_train = df_nuevo_train.drop(columns=[target_column])
target_train = df_nuevo_train[target_column]

features_test = df_nuevo_test.drop(columns=[target_column])

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(features_train, target_train)

predicted_classes = model.predict(features_test)

predicted_df = df_nuevo_test.copy()
predicted_df[target_column] = predicted_classes


      age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
732  57.0     156.0  173.0    119.0      3.0    2.0            0            0   
733  52.0     160.0  196.0    165.0      0.0    0.0            1            0   
734  48.0     100.0  223.0    100.0      0.0    0.0            1            0   
735  62.0     115.0    0.0    128.0      2.5    1.0            1            0   
736  51.0     110.0  175.0    123.0      0.6    0.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
911  54.0     200.0  198.0    142.0      2.0    2.0            1            0   
912  55.0     110.0  214.0    180.0      0.5    0.0            0            1   
913  67.0     152.0  212.0    150.0      0.8    0.0            0            0   
914  59.0     170.0  288.0    159.0      0.2    0.0            0            0   
915  58.0     130.0  203.0    140.0      0.5    1.0            1            0   

     restecg_2.0  cp_1.0  .

In [115]:
predicted_df

age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
732  57.0     156.0  173.0    119.0      3.0    2.0            0            0   
733  52.0     160.0  196.0    165.0      0.0    0.0            1            0   
734  48.0     100.0  223.0    100.0      0.0    0.0            1            0   
735  62.0     115.0    0.0    128.0      2.5    1.0            1            0   
736  51.0     110.0  175.0    123.0      0.6    0.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
911  54.0     200.0  198.0    142.0      2.0    2.0            1            0   
912  55.0     110.0  214.0    180.0      0.5    0.0            0            1   
913  67.0     152.0  212.0    150.0      0.8    0.0            0            0   
914  59.0     170.0  288.0    159.0      0.2    0.0            0            0   
915  58.0     130.0  203.0    140.0      0.5    1.0            1            0   

     restecg_2.0  cp_1.0  ...  thal_3.0  thal_6.0  thal_7.0  sex_0.0  sex_1.0  \
732            1       0  ...         1         0         0        0        1   
733            0       0  ...         1         0         0        0        1   
734            0       0  ...         1         0         0        0        1   
735            0       0  ...         1         0         0        0        1   
736            0       0  ...         1         0         0        0        1   
..           ...     ...  ...       ...       ...       ...      ...      ...   
911            0       0  ...         1         0         0        0        1   
912            0       0  ...         1         0         0        0        1   
913            1       0  ...         0         0         1        0        1   
914            1       1  ...         0         0         1        0        1   
915            0       0  ...         1         0         0        0        1   

     fbs_0.0  fbs_1.0  exang_0.0  exang_1.0  score_by_correlation  
732        1        0          0          1              3.187019  
733        1        0          1          0              3.138204  
734        1        0          1          0              3.138204  
735        1        0          0          1              3.284209  
736        1        0          1          0              2.672916  
..       ...      ...        ...        ...                   ...  
911        1        0          0          1              3.507882  
912        0        1          1          0              3.462400  
913        1        0          1          0              2.866139  
914        1        0          1          0              3.108005  
915        0        1          1          0              3.507882  

[184 rows x 30 columns]

In [118]:
predicted_df['ID'] = range(len(predicted_df))
predicted_df[['ID', 'label']].to_csv('try11_data.csv', index=False)

In [119]:
try11_df = pd.read_csv('try11_data.csv')

In [120]:
try11_df

ID  label
0      0    2.0
1      1    0.0
2      2    0.0
3      3    1.0
4      4    0.0
..   ...    ...
179  179    2.0
180  180    0.0
181  181    0.0
182  182    0.0
183  183    1.0

[184 rows x 2 columns]

In [148]:
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from sklearn.impute import SimpleImputer

target_column = 'label'
features_train = df_nuevo_train.drop(columns=[target_column])
target_train = df_nuevo_train[target_column]

features_test = df_nuevo_test.drop(columns=[target_column])

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
xgb_classifier = XGBClassifier()
logistic_regression = LogisticRegression()
knn_classifier = KNeighborsClassifier()

ensemble_classifier = VotingClassifier(estimators=[
    ('rf', rf_classifier),
    ('xgb', xgb_classifier),
    ('logistic', logistic_regression),
    ('knn', knn_classifier)
], voting='hard')

ensemble_classifier.fit(features_train, target_train)

predicted_classes = ensemble_classifier.predict(features_test)

predicted_df2 = df_nuevo_test.copy()
predicted_df2[target_column] = predicted_classes


      age  trestbps   chol  thalach  oldpeak  label  restecg_0.0  restecg_1.0  \
732  57.0     156.0  173.0    119.0      3.0    2.0            0            0   
733  52.0     160.0  196.0    165.0      0.0    0.0            1            0   
734  48.0     100.0  223.0    100.0      0.0    0.0            1            0   
735  62.0     115.0    0.0    128.0      2.5    1.0            1            0   
736  51.0     110.0  175.0    123.0      0.6    0.0            1            0   
..    ...       ...    ...      ...      ...    ...          ...          ...   
911  54.0     200.0  198.0    142.0      2.0    0.0            1            0   
912  55.0     110.0  214.0    180.0      0.5    0.0            0            1   
913  67.0     152.0  212.0    150.0      0.8    0.0            0            0   
914  59.0     170.0  288.0    159.0      0.2    0.0            0            0   
915  58.0     130.0  203.0    140.0      0.5    0.0            1            0   

     restecg_2.0  cp_1.0  .

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
predicted_df2

In [116]:
predicted_df['label'].value_counts()

0.0    103
1.0     35
3.0     25
2.0     21
Name: label, dtype: int64

In [150]:
predicted_df2['label'].value_counts()

0.0    114
1.0     31
3.0     24
2.0     15
Name: label, dtype: int64

In [149]:
predicted_df2['ID'] = range(len(predicted_df2))
predicted_df2[['ID', 'label']].to_csv('try12_data.csv', index=False)

In [ ]:
try12_df = pd.read_csv('try12_data.csv')

In [ ]:
try12_df

In [140]:
from sklearn.model_selection import train_test_split

X = df_nuevo_train.drop(columns=[target_column])
y = df_nuevo_train[target_column]

X_train_full, X_test, y_train_full, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_val, y_train, y_val = train_test_split(X_train_full, y_train_full, test_size=0.25, random_state=42)

print("Conjunto de entrenamiento - Características:", X_train.shape)
print("Conjunto de entrenamiento - Variable Objetivo:", y_train.shape)
print("Conjunto de validación - Características:", X_val.shape)
print("Conjunto de validación - Variable Objetivo:", y_val.shape)
print("Conjunto de prueba - Características:", X_test.shape)
print("Conjunto de prueba - Variable Objetivo:", y_test.shape)
print(147+147+438)


Conjunto de entrenamiento - Características: (438, 29)
Conjunto de entrenamiento - Variable Objetivo: (438,)
Conjunto de validación - Características: (147, 29)
Conjunto de validación - Variable Objetivo: (147,)
Conjunto de prueba - Características: (147, 29)
Conjunto de prueba - Variable Objetivo: (147,)
732


In [146]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_val)

accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Exactitud del modelo de Random Forest en el conjunto de validación:", accuracy_rf)

accuracy = accuracy_score(y_test, y_pred_rf)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred_rf))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))


Exactitud del modelo de Random Forest en el conjunto de validación: 0.5034013605442177
Accuracy: 0.35374149659863946
Classification Report:
              precision    recall  f1-score   support

         0.0       0.46      0.56      0.50        66
         1.0       0.34      0.35      0.35        31
         2.0       0.17      0.17      0.17        18
         3.0       0.07      0.05      0.05        22
         4.0       0.00      0.00      0.00        10

    accuracy                           0.35       147
   macro avg       0.21      0.23      0.21       147
weighted avg       0.31      0.35      0.33       147

Confusion Matrix:
[[37  9 10  9  1]
 [15 11  3  2  0]
 [ 7  6  3  2  0]
 [15  4  2  1  0]
 [ 7  2  0  1  0]]


In [147]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_val)

accuracy_knn = accuracy_score(y_val, y_pred_knn)
print("Exactitud del modelo KNN en el conjunto de validación:", accuracy_knn)

accuracy = accuracy_score(y_test, y_pred_knn)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred_knn))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_knn))


Exactitud del modelo KNN en el conjunto de validación: 0.4217687074829932
Accuracy: 0.3945578231292517
Classification Report:
              precision    recall  f1-score   support

         0.0       0.51      0.67      0.58        66
         1.0       0.27      0.26      0.26        31
         2.0       0.10      0.11      0.11        18
         3.0       0.40      0.18      0.25        22
         4.0       0.00      0.00      0.00        10

    accuracy                           0.39       147
   macro avg       0.25      0.24      0.24       147
weighted avg       0.36      0.39      0.36       147

Confusion Matrix:
[[44 11  9  2  0]
 [15  8  5  3  0]
 [ 9  6  2  1  0]
 [13  2  3  4  0]
 [ 6  3  1  0  0]]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  

In [144]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

xgb_model = XGBClassifier(random_state=42)
xgb_model.fit(X_train, y_train)

y_pred_xgb = xgb_model.predict(X_val)

accuracy_xgb = accuracy_score(y_val, y_pred_xgb)
print("Exactitud del modelo XGBoost en el conjunto de validación:", accuracy_xgb)

accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Exactitud del modelo de Random Forest en el conjunto de validación:", accuracy_rf)

accuracy = accuracy_score(y_test, y_pred_xgb)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred_xgb))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))


Exactitud del modelo XGBoost en el conjunto de validación: 0.5170068027210885
Exactitud del modelo de Random Forest en el conjunto de validación: 0.5034013605442177
Accuracy: 0.5510204081632653
Classification Report:
              precision    recall  f1-score   support

         0.0       0.73      0.85      0.78        66
         1.0       0.46      0.39      0.42        31
         2.0       0.29      0.33      0.31        18
         3.0       0.29      0.27      0.28        22
         4.0       0.50      0.10      0.17        10

    accuracy                           0.55       147
   macro avg       0.45      0.39      0.39       147
weighted avg       0.54      0.55      0.53       147

Confusion Matrix:
[[56  2  4  4  0]
 [14 12  3  2  0]
 [ 3  2  6  6  1]
 [ 3  9  4  6  0]
 [ 1  1  4  3  1]]


In [145]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

regression_model = LogisticRegression(random_state=42)
regression_model.fit(X_train, y_train)

y_pred_regression = regression_model.predict(X_val)

accuracy_regression = accuracy_score(y_val, y_pred_regression)
print("Exactitud del modelo de regresión en el conjunto de validación:", accuracy_regression)

accuracy_rf = accuracy_score(y_val, y_pred_rf)
print("Exactitud del modelo de Random Forest en el conjunto de validación:", accuracy_rf)

accuracy = accuracy_score(y_test, y_pred_regression)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred_regression))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_regression))

Exactitud del modelo de regresión en el conjunto de validación: 0.5170068027210885
Exactitud del modelo de Random Forest en el conjunto de validación: 0.5034013605442177
Accuracy: 0.5510204081632653
Classification Report:
              precision    recall  f1-score   support

         0.0       0.73      0.85      0.78        66
         1.0       0.46      0.39      0.42        31
         2.0       0.29      0.33      0.31        18
         3.0       0.29      0.27      0.28        22
         4.0       0.50      0.10      0.17        10

    accuracy                           0.55       147
   macro avg       0.45      0.39      0.39       147
weighted avg       0.54      0.55      0.53       147

Confusion Matrix:
[[56  2  4  4  0]
 [14 12  3  2  0]
 [ 3  2  6  6  1]
 [ 3  9  4  6  0]
 [ 1  1  4  3  1]]


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
